# Generated by Django 4.2.6 on 2023-10-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile/'),
        ),
    ]
