# Generated by Django 4.2.6 on 2023-10-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordercart',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
